[*]
desktop_bg=#202020
desktop_shadow=#202020
desktop_fg=#E8E8E8
desktop_font=Sans 20
wallpaper=/usr/share/rpd-wallpaper/sunrise.jpg
wallpaper_mode=color
show_documents=1
show_trash=0
show_mounts=1
folder=/home/cpi/Desktop
